/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetCurrentAccount200Response,
} from '../models';
import {
    GetCurrentAccount200ResponseFromJSON,
    GetCurrentAccount200ResponseToJSON,
} from '../models';

/**
 * AccountsApi - interface
 * 
 * @export
 * @interface AccountsApiInterface
 */
export interface AccountsApiInterface {
    /**
     * ログイン中のアカウント情報を取得するAPI
     * @summary Your GET endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    getCurrentAccountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCurrentAccount200Response>>;

    /**
     * ログイン中のアカウント情報を取得するAPI
     * Your GET endpoint
     */
    getCurrentAccount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCurrentAccount200Response>;

}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI implements AccountsApiInterface {

    /**
     * ログイン中のアカウント情報を取得するAPI
     * Your GET endpoint
     */
    async getCurrentAccountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCurrentAccount200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/current_account`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCurrentAccount200ResponseFromJSON(jsonValue));
    }

    /**
     * ログイン中のアカウント情報を取得するAPI
     * Your GET endpoint
     */
    async getCurrentAccount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCurrentAccount200Response> {
        const response = await this.getCurrentAccountRaw(initOverrides);
        return await response.value();
    }

}
