/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetPrograms200Response,
} from '../models';
import {
    GetPrograms200ResponseFromJSON,
    GetPrograms200ResponseToJSON,
} from '../models';

/**
 * ProgramApi - interface
 * 
 * @export
 * @interface ProgramApiInterface
 */
export interface ProgramApiInterface {
    /**
     * 主にマイページ向けの、特定の会員の拝聴可能なRadioプログラムの一覧取得API
     * @summary List of programs available to members
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProgramApiInterface
     */
    getProgramsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPrograms200Response>>;

    /**
     * 主にマイページ向けの、特定の会員の拝聴可能なRadioプログラムの一覧取得API
     * List of programs available to members
     */
    getPrograms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPrograms200Response>;

}

/**
 * 
 */
export class ProgramApi extends runtime.BaseAPI implements ProgramApiInterface {

    /**
     * 主にマイページ向けの、特定の会員の拝聴可能なRadioプログラムの一覧取得API
     * List of programs available to members
     */
    async getProgramsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPrograms200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/programs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPrograms200ResponseFromJSON(jsonValue));
    }

    /**
     * 主にマイページ向けの、特定の会員の拝聴可能なRadioプログラムの一覧取得API
     * List of programs available to members
     */
    async getPrograms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPrograms200Response> {
        const response = await this.getProgramsRaw(initOverrides);
        return await response.value();
    }

}
