name: OpenAPI validation

on:
  pull_request:
    paths:
      - 'openapi.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint OpenAPI
        run: npx @stoplight/spectral-cli lint openapi.yml
