/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChapterOfPlayLogStartChapterIdRequest
 */
export interface ChapterOfPlayLogStartChapterIdRequest {
    /**
     * 
     * @type {number}
     * @memberof ChapterOfPlayLogStartChapterIdRequest
     */
    chapterId?: number;
}

/**
 * Check if a given object implements the ChapterOfPlayLogStartChapterIdRequest interface.
 */
export function instanceOfChapterOfPlayLogStartChapterIdRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChapterOfPlayLogStartChapterIdRequestFromJSON(json: any): ChapterOfPlayLogStartChapterIdRequest {
    return ChapterOfPlayLogStartChapterIdRequestFromJSONTyped(json, false);
}

export function ChapterOfPlayLogStartChapterIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterOfPlayLogStartChapterIdRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chapterId': !exists(json, 'chapterId') ? undefined : json['chapterId'],
    };
}

export function ChapterOfPlayLogStartChapterIdRequestToJSON(value?: ChapterOfPlayLogStartChapterIdRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chapterId': value.chapterId,
    };
}

