/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 音声ファイルとその説明
 * @export
 * @interface Chapter
 */
export interface Chapter {
    /**
     * 
     * @type {number}
     * @memberof Chapter
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Chapter
     */
    programId?: number;
    /**
     * 
     * @type {number}
     * @memberof Chapter
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    title?: string;
    /**
     * 固定表示ON/OFF
     * @type {boolean}
     * @memberof Chapter
     */
    isAttachedPin?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    mediaUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof Chapter
     */
    playTimeSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    deletedAt?: string | null;
}

/**
 * Check if a given object implements the Chapter interface.
 */
export function instanceOfChapter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChapterFromJSON(json: any): Chapter {
    return ChapterFromJSONTyped(json, false);
}

export function ChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Chapter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'programId': !exists(json, 'programId') ? undefined : json['programId'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'isAttachedPin': !exists(json, 'isAttachedPin') ? undefined : json['isAttachedPin'],
        'mediaUrl': !exists(json, 'mediaUrl') ? undefined : json['mediaUrl'],
        'playTimeSeconds': !exists(json, 'playTimeSeconds') ? undefined : json['playTimeSeconds'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'deletedAt': !exists(json, 'deletedAt') ? undefined : json['deletedAt'],
    };
}

export function ChapterToJSON(value?: Chapter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'programId': value.programId,
        'order': value.order,
        'title': value.title,
        'isAttachedPin': value.isAttachedPin,
        'mediaUrl': value.mediaUrl,
        'playTimeSeconds': value.playTimeSeconds,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'deletedAt': value.deletedAt,
    };
}

