/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChapterOfPlayLogEndChapterIdRequest
 */
export interface ChapterOfPlayLogEndChapterIdRequest {
    /**
     * 
     * @type {number}
     * @memberof ChapterOfPlayLogEndChapterIdRequest
     */
    programId: number;
    /**
     * 
     * @type {number}
     * @memberof ChapterOfPlayLogEndChapterIdRequest
     */
    chapterId: number;
    /**
     * 
     * @type {number}
     * @memberof ChapterOfPlayLogEndChapterIdRequest
     */
    elapsedSeconds: number;
}

/**
 * Check if a given object implements the ChapterOfPlayLogEndChapterIdRequest interface.
 */
export function instanceOfChapterOfPlayLogEndChapterIdRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "programId" in value;
    isInstance = isInstance && "chapterId" in value;
    isInstance = isInstance && "elapsedSeconds" in value;

    return isInstance;
}

export function ChapterOfPlayLogEndChapterIdRequestFromJSON(json: any): ChapterOfPlayLogEndChapterIdRequest {
    return ChapterOfPlayLogEndChapterIdRequestFromJSONTyped(json, false);
}

export function ChapterOfPlayLogEndChapterIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterOfPlayLogEndChapterIdRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'programId': json['programId'],
        'chapterId': json['chapterId'],
        'elapsedSeconds': json['elapsedSeconds'],
    };
}

export function ChapterOfPlayLogEndChapterIdRequestToJSON(value?: ChapterOfPlayLogEndChapterIdRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'programId': value.programId,
        'chapterId': value.chapterId,
        'elapsedSeconds': value.elapsedSeconds,
    };
}

