/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Plan } from './Plan';
import {
    PlanFromJSON,
    PlanFromJSONTyped,
    PlanToJSON,
} from './Plan';

/**
 * 
 * @export
 * @interface Club
 */
export interface Club {
    /**
     * 
     * @type {number}
     * @memberof Club
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    overview: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    clubColor: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    url: string;
    /**
     * 
     * @type {Array<Plan>}
     * @memberof Club
     */
    programAttachedPlans: Array<Plan>;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    twitterUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    facebookUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    lineUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    instagramUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    youtubeUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    tiktokUrl?: string;
}

/**
 * Check if a given object implements the Club interface.
 */
export function instanceOfClub(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "overview" in value;
    isInstance = isInstance && "clubColor" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "programAttachedPlans" in value;

    return isInstance;
}

export function ClubFromJSON(json: any): Club {
    return ClubFromJSONTyped(json, false);
}

export function ClubFromJSONTyped(json: any, ignoreDiscriminator: boolean): Club {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'overview': json['overview'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'clubColor': json['clubColor'],
        'url': json['url'],
        'programAttachedPlans': ((json['programAttachedPlans'] as Array<any>).map(PlanFromJSON)),
        'twitterUrl': !exists(json, 'twitter_url') ? undefined : json['twitter_url'],
        'facebookUrl': !exists(json, 'facebook_url') ? undefined : json['facebook_url'],
        'lineUrl': !exists(json, 'line_url') ? undefined : json['line_url'],
        'instagramUrl': !exists(json, 'instagram_url') ? undefined : json['instagram_url'],
        'youtubeUrl': !exists(json, 'youtube_url') ? undefined : json['youtube_url'],
        'tiktokUrl': !exists(json, 'tiktok_url') ? undefined : json['tiktok_url'],
    };
}

export function ClubToJSON(value?: Club | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'slug': value.slug,
        'overview': value.overview,
        'icon': value.icon,
        'clubColor': value.clubColor,
        'url': value.url,
        'programAttachedPlans': ((value.programAttachedPlans as Array<any>).map(PlanToJSON)),
        'twitter_url': value.twitterUrl,
        'facebook_url': value.facebookUrl,
        'line_url': value.lineUrl,
        'instagram_url': value.instagramUrl,
        'youtube_url': value.youtubeUrl,
        'tiktok_url': value.tiktokUrl,
    };
}

