/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Plan } from './Plan';
import {
    PlanFromJSON,
    PlanFromJSONTyped,
    PlanToJSON,
} from './Plan';

/**
 * 
 * @export
 * @interface Club
 */
export interface Club {
    /**
     * 
     * @type {number}
     * @memberof Club
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    overview?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    clubColor?: string;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    url?: string;
    /**
     * 
     * @type {Array<Plan>}
     * @memberof Club
     */
    programAttachedPlans?: Array<Plan>;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    twitterUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    facebookUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    lineUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    instagramUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    youtubeUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Club
     */
    tiktokUrl?: string | null;
}

/**
 * Check if a given object implements the Club interface.
 */
export function instanceOfClub(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClubFromJSON(json: any): Club {
    return ClubFromJSONTyped(json, false);
}

export function ClubFromJSONTyped(json: any, ignoreDiscriminator: boolean): Club {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'overview': !exists(json, 'overview') ? undefined : json['overview'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'clubColor': !exists(json, 'clubColor') ? undefined : json['clubColor'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'programAttachedPlans': !exists(json, 'programAttachedPlans') ? undefined : ((json['programAttachedPlans'] as Array<any>).map(PlanFromJSON)),
        'twitterUrl': !exists(json, 'twitter_url') ? undefined : json['twitter_url'],
        'facebookUrl': !exists(json, 'facebook_url') ? undefined : json['facebook_url'],
        'lineUrl': !exists(json, 'line_url') ? undefined : json['line_url'],
        'instagramUrl': !exists(json, 'instagram_url') ? undefined : json['instagram_url'],
        'youtubeUrl': !exists(json, 'youtube_url') ? undefined : json['youtube_url'],
        'tiktokUrl': !exists(json, 'tiktok_url') ? undefined : json['tiktok_url'],
    };
}

export function ClubToJSON(value?: Club | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'slug': value.slug,
        'overview': value.overview,
        'icon': value.icon,
        'clubColor': value.clubColor,
        'url': value.url,
        'programAttachedPlans': value.programAttachedPlans === undefined ? undefined : ((value.programAttachedPlans as Array<any>).map(PlanToJSON)),
        'twitter_url': value.twitterUrl,
        'facebook_url': value.facebookUrl,
        'line_url': value.lineUrl,
        'instagram_url': value.instagramUrl,
        'youtube_url': value.youtubeUrl,
        'tiktok_url': value.tiktokUrl,
    };
}

