/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProgramRequestChaptersInner
 */
export interface CreateProgramRequestChaptersInner {
    /**
     * 
     * @type {string}
     * @memberof CreateProgramRequestChaptersInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProgramRequestChaptersInner
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProgramRequestChaptersInner
     */
    s3Url?: string;
    /**
     * mineType 例：image/jpeg
     * @type {string}
     * @memberof CreateProgramRequestChaptersInner
     */
    contentType?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProgramRequestChaptersInner
     */
    playTime?: number;
}

/**
 * Check if a given object implements the CreateProgramRequestChaptersInner interface.
 */
export function instanceOfCreateProgramRequestChaptersInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateProgramRequestChaptersInnerFromJSON(json: any): CreateProgramRequestChaptersInner {
    return CreateProgramRequestChaptersInnerFromJSONTyped(json, false);
}

export function CreateProgramRequestChaptersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProgramRequestChaptersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'fileName': !exists(json, 'fileName') ? undefined : json['fileName'],
        's3Url': !exists(json, 's3Url') ? undefined : json['s3Url'],
        'contentType': !exists(json, 'contentType') ? undefined : json['contentType'],
        'playTime': !exists(json, 'playTime') ? undefined : json['playTime'],
    };
}

export function CreateProgramRequestChaptersInnerToJSON(value?: CreateProgramRequestChaptersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'fileName': value.fileName,
        's3Url': value.s3Url,
        'contentType': value.contentType,
        'playTime': value.playTime,
    };
}

