/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Program } from './Program';
import {
    ProgramFromJSON,
    ProgramFromJSONTyped,
    ProgramToJSON,
} from './Program';

/**
 * 
 * @export
 * @interface CreateProgram200Response
 */
export interface CreateProgram200Response {
    /**
     * 
     * @type {Program}
     * @memberof CreateProgram200Response
     */
    program?: Program;
}

/**
 * Check if a given object implements the CreateProgram200Response interface.
 */
export function instanceOfCreateProgram200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateProgram200ResponseFromJSON(json: any): CreateProgram200Response {
    return CreateProgram200ResponseFromJSONTyped(json, false);
}

export function CreateProgram200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProgram200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'program': !exists(json, 'program') ? undefined : ProgramFromJSON(json['program']),
    };
}

export function CreateProgram200ResponseToJSON(value?: CreateProgram200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'program': ProgramToJSON(value.program),
    };
}

