/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProgramRequestChaptersInner
 */
export interface CreateProgramRequestChaptersInner {
    /**
     * 
     * @type {string}
     * @memberof CreateProgramRequestChaptersInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProgramRequestChaptersInner
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProgramRequestChaptersInner
     */
    mediaUrl?: string;
    /**
     * mineType 例：image/jpeg
     * @type {string}
     * @memberof CreateProgramRequestChaptersInner
     */
    contentType?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProgramRequestChaptersInner
     */
    playTimeSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateProgramRequestChaptersInner
     */
    order?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateProgramRequestChaptersInner
     */
    id?: number | null;
}

/**
 * Check if a given object implements the CreateProgramRequestChaptersInner interface.
 */
export function instanceOfCreateProgramRequestChaptersInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateProgramRequestChaptersInnerFromJSON(json: any): CreateProgramRequestChaptersInner {
    return CreateProgramRequestChaptersInnerFromJSONTyped(json, false);
}

export function CreateProgramRequestChaptersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProgramRequestChaptersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'fileName': !exists(json, 'fileName') ? undefined : json['fileName'],
        'mediaUrl': !exists(json, 'mediaUrl') ? undefined : json['mediaUrl'],
        'contentType': !exists(json, 'contentType') ? undefined : json['contentType'],
        'playTimeSeconds': !exists(json, 'playTimeSeconds') ? undefined : json['playTimeSeconds'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function CreateProgramRequestChaptersInnerToJSON(value?: CreateProgramRequestChaptersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'fileName': value.fileName,
        'mediaUrl': value.mediaUrl,
        'contentType': value.contentType,
        'playTimeSeconds': value.playTimeSeconds,
        'order': value.order,
        'id': value.id,
    };
}

