/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReactionComment } from './ReactionComment';
import {
    ReactionCommentFromJSON,
    ReactionCommentFromJSONTyped,
    ReactionCommentToJSON,
} from './ReactionComment';

/**
 * 
 * @export
 * @interface CreateProgramReactionComment200Response
 */
export interface CreateProgramReactionComment200Response {
    /**
     * 
     * @type {ReactionComment}
     * @memberof CreateProgramReactionComment200Response
     */
    reactionComment?: ReactionComment;
}

/**
 * Check if a given object implements the CreateProgramReactionComment200Response interface.
 */
export function instanceOfCreateProgramReactionComment200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateProgramReactionComment200ResponseFromJSON(json: any): CreateProgramReactionComment200Response {
    return CreateProgramReactionComment200ResponseFromJSONTyped(json, false);
}

export function CreateProgramReactionComment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProgramReactionComment200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reactionComment': !exists(json, 'reactionComment') ? undefined : ReactionCommentFromJSON(json['reactionComment']),
    };
}

export function CreateProgramReactionComment200ResponseToJSON(value?: CreateProgramReactionComment200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reactionComment': ReactionCommentToJSON(value.reactionComment),
    };
}

