/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Chapter } from './Chapter';
import {
    ChapterFromJSON,
    ChapterFromJSONTyped,
    ChapterToJSON,
} from './Chapter';

/**
 * 
 * @export
 * @interface DeleteChapterId200Response
 */
export interface DeleteChapterId200Response {
    /**
     * 
     * @type {Chapter}
     * @memberof DeleteChapterId200Response
     */
    chapter?: Chapter;
}

/**
 * Check if a given object implements the DeleteChapterId200Response interface.
 */
export function instanceOfDeleteChapterId200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteChapterId200ResponseFromJSON(json: any): DeleteChapterId200Response {
    return DeleteChapterId200ResponseFromJSONTyped(json, false);
}

export function DeleteChapterId200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteChapterId200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chapter': !exists(json, 'chapter') ? undefined : ChapterFromJSON(json['chapter']),
    };
}

export function DeleteChapterId200ResponseToJSON(value?: DeleteChapterId200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chapter': ChapterToJSON(value.chapter),
    };
}

