/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Club } from './Club';
import {
    ClubFromJSON,
    ClubFromJSONTyped,
    ClubToJSON,
} from './Club';

/**
 * 
 * @export
 * @interface GetClubById200Response
 */
export interface GetClubById200Response {
    /**
     * 
     * @type {Club}
     * @memberof GetClubById200Response
     */
    club: Club;
}

/**
 * Check if a given object implements the GetClubById200Response interface.
 */
export function instanceOfGetClubById200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "club" in value;

    return isInstance;
}

export function GetClubById200ResponseFromJSON(json: any): GetClubById200Response {
    return GetClubById200ResponseFromJSONTyped(json, false);
}

export function GetClubById200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClubById200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'club': ClubFromJSON(json['club']),
    };
}

export function GetClubById200ResponseToJSON(value?: GetClubById200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'club': ClubToJSON(value.club),
    };
}

