/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlayLog } from './PlayLog';
import {
    PlayLogFromJSON,
    PlayLogFromJSONTyped,
    PlayLogToJSON,
} from './PlayLog';

/**
 * 
 * @export
 * @interface GetPlayLogs200Response
 */
export interface GetPlayLogs200Response {
    /**
     * 
     * @type {Array<PlayLog>}
     * @memberof GetPlayLogs200Response
     */
    playLogs: Array<PlayLog>;
}

/**
 * Check if a given object implements the GetPlayLogs200Response interface.
 */
export function instanceOfGetPlayLogs200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "playLogs" in value;

    return isInstance;
}

export function GetPlayLogs200ResponseFromJSON(json: any): GetPlayLogs200Response {
    return GetPlayLogs200ResponseFromJSONTyped(json, false);
}

export function GetPlayLogs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlayLogs200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'playLogs': ((json['playLogs'] as Array<any>).map(PlayLogFromJSON)),
    };
}

export function GetPlayLogs200ResponseToJSON(value?: GetPlayLogs200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'playLogs': ((value.playLogs as Array<any>).map(PlayLogToJSON)),
    };
}

