/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Chapter } from './Chapter';
import {
    ChapterFromJSON,
    ChapterFromJSONTyped,
    ChapterToJSON,
} from './Chapter';

/**
 * 
 * @export
 * @interface GetProgramChapters200Response
 */
export interface GetProgramChapters200Response {
    /**
     * 
     * @type {Array<Chapter>}
     * @memberof GetProgramChapters200Response
     */
    chapters?: Array<Chapter>;
}

/**
 * Check if a given object implements the GetProgramChapters200Response interface.
 */
export function instanceOfGetProgramChapters200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetProgramChapters200ResponseFromJSON(json: any): GetProgramChapters200Response {
    return GetProgramChapters200ResponseFromJSONTyped(json, false);
}

export function GetProgramChapters200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProgramChapters200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chapters': !exists(json, 'chapters') ? undefined : ((json['chapters'] as Array<any>).map(ChapterFromJSON)),
    };
}

export function GetProgramChapters200ResponseToJSON(value?: GetProgramChapters200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chapters': value.chapters === undefined ? undefined : ((value.chapters as Array<any>).map(ChapterToJSON)),
    };
}

