/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ReactionComment,
    ReactionCommentFromJSON,
    ReactionCommentFromJSONTyped,
    ReactionCommentToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 
     * @type {Array<ReactionComment>}
     * @memberof InlineResponse2002
     */
    reactionComments: Array<ReactionComment>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2002
     */
    nextCursor?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2002
     */
    totalCounts?: number;
}

export function InlineResponse2002FromJSON(json: any): InlineResponse2002 {
    return InlineResponse2002FromJSONTyped(json, false);
}

export function InlineResponse2002FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2002 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reactionComments': ((json['reactionComments'] as Array<any>).map(ReactionCommentFromJSON)),
        'nextCursor': !exists(json, 'nextCursor') ? undefined : json['nextCursor'],
        'totalCounts': !exists(json, 'totalCounts') ? undefined : json['totalCounts'],
    };
}

export function InlineResponse2002ToJSON(value?: InlineResponse2002 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reactionComments': ((value.reactionComments as Array<any>).map(ReactionCommentToJSON)),
        'nextCursor': value.nextCursor,
        'totalCounts': value.totalCounts,
    };
}

