/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReactionComment } from './ReactionComment';
import {
    ReactionCommentFromJSON,
    ReactionCommentFromJSONTyped,
    ReactionCommentToJSON,
} from './ReactionComment';

/**
 * 
 * @export
 * @interface PostProgramReactionComments200Response
 */
export interface PostProgramReactionComments200Response {
    /**
     * 
     * @type {ReactionComment}
     * @memberof PostProgramReactionComments200Response
     */
    reactionComment?: ReactionComment;
}

/**
 * Check if a given object implements the PostProgramReactionComments200Response interface.
 */
export function instanceOfPostProgramReactionComments200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostProgramReactionComments200ResponseFromJSON(json: any): PostProgramReactionComments200Response {
    return PostProgramReactionComments200ResponseFromJSONTyped(json, false);
}

export function PostProgramReactionComments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostProgramReactionComments200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reactionComment': !exists(json, 'reactionComment') ? undefined : ReactionCommentFromJSON(json['reactionComment']),
    };
}

export function PostProgramReactionComments200ResponseToJSON(value?: PostProgramReactionComments200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reactionComment': ReactionCommentToJSON(value.reactionComment),
    };
}

