/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPublishPreSignedUrl200Response
 */
export interface PostPublishPreSignedUrl200Response {
    /**
     * 
     * @type {string}
     * @memberof PostPublishPreSignedUrl200Response
     */
    preSignedUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PostPublishPreSignedUrl200Response
     */
    s3Url?: string;
}

/**
 * Check if a given object implements the PostPublishPreSignedUrl200Response interface.
 */
export function instanceOfPostPublishPreSignedUrl200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostPublishPreSignedUrl200ResponseFromJSON(json: any): PostPublishPreSignedUrl200Response {
    return PostPublishPreSignedUrl200ResponseFromJSONTyped(json, false);
}

export function PostPublishPreSignedUrl200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPublishPreSignedUrl200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'preSignedUrl': !exists(json, 'preSignedUrl') ? undefined : json['preSignedUrl'],
        's3Url': !exists(json, 's3Url') ? undefined : json['s3Url'],
    };
}

export function PostPublishPreSignedUrl200ResponseToJSON(value?: PostPublishPreSignedUrl200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'preSignedUrl': value.preSignedUrl,
        's3Url': value.s3Url,
    };
}

