/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostProgramReactionCommentsRequest
 */
export interface PostProgramReactionCommentsRequest {
    /**
     * 
     * @type {number}
     * @memberof PostProgramReactionCommentsRequest
     */
    programId?: number;
    /**
     * 
     * @type {string}
     * @memberof PostProgramReactionCommentsRequest
     */
    contents?: string;
}

/**
 * Check if a given object implements the PostProgramReactionCommentsRequest interface.
 */
export function instanceOfPostProgramReactionCommentsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostProgramReactionCommentsRequestFromJSON(json: any): PostProgramReactionCommentsRequest {
    return PostProgramReactionCommentsRequestFromJSONTyped(json, false);
}

export function PostProgramReactionCommentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostProgramReactionCommentsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'programId': !exists(json, 'programId') ? undefined : json['programId'],
        'contents': !exists(json, 'contents') ? undefined : json['contents'],
    };
}

export function PostProgramReactionCommentsRequestToJSON(value?: PostProgramReactionCommentsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'programId': value.programId,
        'contents': value.contents,
    };
}

