/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ユーザプロファイル（会員、オーナー、通りすがりの人がありえる）
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    thumbnail?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Profile
     */
    isPublicProfile?: boolean;
    /**
     * owner or member or passerby
     * @type {string}
     * @memberof Profile
     */
    type?: string;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'thumbnail': !exists(json, 'thumbnail') ? undefined : json['thumbnail'],
        'isPublicProfile': !exists(json, 'isPublicProfile') ? undefined : json['isPublicProfile'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function ProfileToJSON(value?: Profile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'thumbnail': value.thumbnail,
        'isPublicProfile': value.isPublicProfile,
        'type': value.type,
    };
}

