/* tslint:disable */
/* eslint-disable */
/**
 * radio_openapi
 * radio_openapi
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@anycloud.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ユーザプロファイル（会員、オーナー、通りすがりの人がありえる）
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    thumbnail?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Profile
     */
    isPublicProfile: boolean;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    type: ProfileTypeEnum;
}


/**
 * @export
 */
export const ProfileTypeEnum = {
    Owner: 'OWNER',
    Member: 'MEMBER',
    Passerby: 'PASSERBY'
} as const;
export type ProfileTypeEnum = typeof ProfileTypeEnum[keyof typeof ProfileTypeEnum];


/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "isPublicProfile" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'thumbnail': !exists(json, 'thumbnail') ? undefined : json['thumbnail'],
        'isPublicProfile': json['isPublicProfile'],
        'type': json['type'],
    };
}

export function ProfileToJSON(value?: Profile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'thumbnail': value.thumbnail,
        'isPublicProfile': value.isPublicProfile,
        'type': value.type,
    };
}

